export { default as Main } from './Main/Main.js'
export { default as Detail } from './Detail/Detail.js'
export { default as Search } from './Search/Search.js'
export { default as Enter } from './Enter/Enter.js'
export { default as Quiz } from './Quiz/Quiz.js'
